# Generated by Django 3.2.3 on 2021-06-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availablility',
            field=models.BooleanField(default=True),
        ),
    ]
